spring.application.name=BuildFlow
# Email Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-dahamserasinghe542@gmail.com
spring.mail.password=bfoa uipc tmhj dxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true