package lk.ijse.buildflow.service.impl;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lk.ijse.buildflow.service.DocumentGenerator;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

@Service("openPdfGenerator")
public class OpenPdfGeneratorImpl implements DocumentGenerator {

    @Override
    public byte[] generateQuotationPdf(String customerName, String modelName, Double price, Integer bedrooms, Double area) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            Font fontTitle = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);
            Paragraph title = new Paragraph("BuildFlow Official Quotation", fontTitle);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph("\n"));

            document.add(new Paragraph("Customer Name: " + customerName));
            document.add(new Paragraph("Model Selected: " + modelName));
            document.add(new Paragraph("Quotation Date: " + LocalDate.now()));
            document.add(new Paragraph("\n"));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.addCell("House Model Name");
            table.addCell(modelName);

            table.addCell("Number of Bedrooms");
            table.addCell(String.valueOf(bedrooms));

            table.addCell("Floor Area");
            table.addCell(area + " sq.ft");

            table.addCell("Estimated Total Cost");
            table.addCell("LKR " + String.format("%.2f", price));

            document.add(table);

            document.add(new Paragraph("\n\n* This is an automated quotation generated by BuildFlow System."));

            document.close();
        } catch (DocumentException e) {
            throw new RuntimeException("Error occurred while creating PDF", e);
        }

        return out.toByteArray();
    }
}
